### ISSUE TITLE
Wakatime stuck at VS Code initializing

### ISSUE THREAD

**Issue by plavi88** [wakatime/vscode-wakatime#156]
Hi all,

I tried to install the Wakatime to VS Code today but it got stuck at initializing. I followed the instructions for troubleshooting and this is what I get:

![Screen Shot 2020-08-24 at 1 21 09 PM](https://user-images.githubusercontent.com/57862695/91039551-0de07a80-e60d-11ea-81e5-c6f2dcb1643f.png)

Could you please help?

Thanks

**Comment by subedigaurav** [comment]
I too am having this issue. The log is basically the same and is stuck at downloading wakatime-cli.

**Comment by khanguslee** [comment]
Just installed today and got the same issue as @subedigaurav. Attached is my vscode log:
<img width="553" alt="Screen Shot 2020-08-24 at 10 33 57 pm" src="https://user-images.githubusercontent.com/18709969/91045223-e6fc6580-e659-11ea-8217-aefe268094a3.png">

**Comment by jeffryang24** [comment]
Same issue before at #155. You can rolled back to v4.0.0 to get the last known working version. :bow:

**Comment by subedigaurav** [comment]
Thanks @khanguslee . Manually downloading the cli did the trick. 🚀

**Comment by alanhamlett** [comment]
Fixed in v4.0.5.

**Comment by iamtodor** [comment]
@alanhamlett Probably is not fixed. I have v4.0.8 and have the same issue. All the details: https://github.com/wakatime/vscode-wakatime/issues/144#issuecomment-695764599

**Comment by ciekawy** [comment]
same here - macos v4.0.8. Also initially it caused all other extensions to crash...

**Comment by ciekawy** [comment]
even manual download does not seem to help

**Comment by hezhizhen** [comment]
<img width="1308" alt="Screen Shot 2020-10-10 at 00 57 36" src="https://user-images.githubusercontent.com/7611700/95610880-9919b080-0a93-11eb-9ff1-05d11eefe226.png">

**Comment by gandarez** [comment]
For who is having problems pelase try enabling or disabling `standalone` flag. To do it in VSCode type CTRL + P then `>WakaTime: Open Config File...` and set `standalone = <bool>` (true or false).

Alternatively here are the standalone urls per OS.
macOS -> https://wakatime-cli.s3-us-west-2.amazonaws.com/mac-x86-64/wakatime-cli.zip
windows x86 -> https://wakatime-cli.s3-us-west-2.amazonaws.com/windows-x86-32/wakatime-cli.zip
windows x64 -> https://wakatime-cli.s3-us-west-2.amazonaws.com/windows-x86-64/wakatime-cli.zip
linux -> https://wakatime-cli.s3-us-west-2.amazonaws.com/linux-x86-64/wakatime-cli.zip

**Comment by ciekawy** [comment]
well after digging deeper seems that I'm facing actually 2yo ticket... https://github.com/wakatime/wakatime/issues/155

**Comment by ciekawy** [comment]
I tried to `brew install wakatime-cli`, then reinstall wakatime vscode extension and restart twice for both `standalone` `true` and `false` - all the time getting messages from first post (modulo `standalone` in the logs which depends on the variable set).

**Comment by ciekawy** [comment]
ok, I think I finally got it working after applying https://github.com/wakatime/vscode-wakatime/issues/140#issuecomment-678935032 (akshay-s-770 commented on Aug 24):

quoting here:
> Its due to wakatime-cli.zip, it takes some hours to download. you should download it manual.
> in my case i downloaded the zip manually and unzipped .vscode\extensions\wakatime.vscode-wakatime-4.0.5
> I downloaded the zip from this URL https://wakatime-cli.s3-us-west-2.amazonaws.com/windows-x86-64/wakatime-cli.zip

Just for Mac I did use https://wakatime-cli.s3-us-west-2.amazonaws.com/mac-x86-64/wakatime-cli.zip

**Comment by luojiego** [comment]
Downloading from amazonaws in China is too difficult, can you add some sources to solve this problem?

**Comment by luojiego** [comment]
Manually downloading wakatime-cli solved my problem。Thanks @ciekawy

**Comment by iamtodor** [comment]
Faced this issue again. 
Logs from `.wakatime.log`
```json
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:189","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: failed making request to \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": Post \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)","now":"2021-08-20T13:46:23+03:00","version":"v1.18.10"}
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:189","func":"runCmd","level":"error","message":"failed to run command: failed to fetch today summary due to api error: failed fetching summaries from api: invalid response status from \"https://api.wakatime.com/api/v1/users/current/summaries\". got: 502, want: 200. body: \"{\\\"code\\\": 502, \\\"error\\\": \\\"Server Maintenance... This shouldn't take long.\\\"}\\n\"","now":"2021-08-20T13:47:14+03:00","version":"v1.18.10"}
```

Logs from `Toggle Developer Tools`
```
[Extension Host] [WakaTime][DEBUG] Initializing WakaTime v15.0.1
workbench.desktop.main.js:sourcemap:62 [Extension Host] [WakaTime][DEBUG] GitHub API Response 304
workbench.desktop.main.js:sourcemap:62 [Extension Host] [WakaTime][DEBUG] Downloading wakatime-cli v1.18.11...
workbench.desktop.main.js:sourcemap:62 [Extension Host] Starting WebSocket: RAW/api/kernels/cea908f4-5460-4266-8833-a48955a1756b
workbench.desktop.main.js:sourcemap:62 [Extension Host] Kernel: connected (cea908f4-5460-4266-8833-a48955a1756b)
workbench.desktop.main.js:sourcemap:62 [Extension Host] Kernel: starting (cea908f4-5460-4266-8833-a48955a1756b)
workbench.desktop.main.js:sourcemap:62 [Extension Host] [WakaTime][DEBUG] Extracting wakatime-cli into "/Users/user/.wakatime"...
workbench.desktop.main.js:sourcemap:62 [Extension Host] [WakaTime][DEBUG] Finished extracting wakatime-cli.
```

Manual downloading didn't help:
```
>> wget https://wakatime-cli.s3-us-west-2.amazonaws.com/mac-x86-64/wakatime-cli.zip
>> unzip wakatime-cli.zip
>> cp -r wakatime-cli .vscode/extensions/wakatime.vscode-wakatime-4.0.8
>> cp wakatime-cli.zip .vscode/extensions/wakatime.vscode-wakatime-4.0.8
>> ls -la .vscode/extensions/wakatime.vscode-wakatime-15.0.1
total 39568
-rw-r--r--   1 usr  staff    14K Aug 18 15:11 CHANGELOG.md
-rw-r--r--   1 usr  staff   1.5K Aug 18 15:11 LICENSE.txt
-rw-r--r--   1 usr  staff   3.3K Aug 18 15:11 README.md
drwxr-xr-x   4 usr  staff   128B Aug 18 15:11 dist
drwxr-xr-x   6 usr  staff   192B Aug 18 15:11 images
-rw-r--r--   1 usr  staff   8.3M Aug 18 15:11 onivim2-trace.log
-rw-r--r--   1 usr  staff   2.8K Aug 18 15:11 package.json
drwxr-xr-x  71 usr  staff   2.2K Aug 23 17:43 wakatime-cli
-rw-r--r--   1 usr  staff    11M Mar  3  2020 wakatime-cli.zip
```

MacOS: 11.5.2
VSCode: 1.59.1
Wakatime: 15.0.1

**Comment by alanhamlett** [comment]
> Downloading from amazonaws in China is too difficult, can you add some sources to solve this problem?

We're switching to GitHub Releases for downloading wakatime-cli. However, we currently download both the new wakatime-cli and the legacy wakatime-cli to fallback on any errors. So we still use AWS for the legacy Python wakatime-cli, but that will go away once it's safe to fully use the new wakatime-cli.

**Comment by iamtodor** [comment]
@gandarez yeah, I confirm it:
```
>>> ls -la .wakatime
total 0
drwxr-xr-x   4 usr  staff   128 Aug 25 10:39 .
drwxr-xr-x+ 63 usr  staff  2016 Aug 25 10:40 ..
drwxr-xr-x  71 usr  staff  2272 Mar 22 11:58 wakatime-cli
drwxr-xr-x  18 usr  staff   576 Apr 15 12:20 wakatime-master
```

Currently I have `wakatime-cli` in `.vscode/extensions/wakatime.vscode-wakatime-15.0.1` and in `~/.wakatime` folder

**Comment by gandarez** [comment]
Please add `new_beta_cli = true` under `[settings]` in your `~/.wakatime.cfg` and restart VSCODE. You'll notice a new binary called `wakatime-cli-<os>-<arch>`. Let me know if it works for you.

**Comment by iamtodor** [comment]
@gandarez still the same: `Wakatime Initializing...`

**Comment by gandarez** [comment]
Let's try it out. Wuld mind joining our slack and pinging me there? 
https://wakatime.com/community

**Comment by alanhamlett** [comment]
> Currently I have wakatime-cli in .vscode/extensions/wakatime.vscode-wakatime-15.0.1 and in ~/.wakatime folder

The one in your extensions folder isn't used anymore, now we only use the `~/.wakatime` folder. Also, `new_beta_cli = true` is the default currently.

You can also book a time to screenshare/Zoom with me and I'll help debug it.

**Comment by alanhamlett** [comment]
My guess is we don't have a wakatime-cli binary for your os/arch combination. Here's the list of Unix-based platforms we currently build for:

* darwin (amd64, arm64)
* freebsd (386, amd64, arm)
* linux (386, amd64, arm, arm64)
* netbsd (386, amd64, arm)
* openbsd (386, amd64, arm, arm64)
