### ISSUE TITLE
Continuously invoked on GitHub Codespaces

### ISSUE THREAD

**Issue by linbudu599** [wakatime/vscode-wakatime#169]
When using in GitHub Codespaces, I cannot close dialog which required `WakaTime API Token`, even if I tap `escape`, it would appear again after seconds until I enter the correct token.

**Comment by JipFr** [comment]
I'm experiencing this as well

**Comment by alanhamlett** [comment]
Should be fixed with v6.0.4. However, can you share the error message from your vscode dev console window with me before upgrading the plugin?

**Comment by JipFr** [comment]
Apologies for the late response. I am currently on 8.0.0 and am still getting it. The error is as follows:
![Screenshot 2021-05-10 at 11 59 19](https://user-images.githubusercontent.com/17685409/117642045-2ab2e300-b187-11eb-8c51-d5b4e3243df6.png)

**Comment by alanhamlett** [comment]
Let's move this into #244.

**Comment by TheDevMinerTV** [comment]
This is still happening.

**Comment by alanhamlett** [comment]
Let's discuss in #362.

**Comment by alanhamlett** [comment]
A duplicate of #1035? I can't reproduce this for some reason... it saves the api key and never asks again for me as long as I'm using the same codespace and not a new one.

**Comment by alanhamlett** [comment]
We have too many issues open for this. Locking this and moving discussion to #362.
