### ISSUE TITLE
Using wrong wakatime-cli binary file name on Linux arm64

### ISSUE THREAD

**Issue by simonSlamka** [wakatime/vscode-wakatime#216]
Hello,

I'm experiencing unexpected behavior in my vscode with the wakatime extension. I have confirmed that my API key is correct.
The log in the home directory is empty.

Repro is to just install the extension, input your API key and get it to attempt to sync.

VSCode:
![image](https://user-images.githubusercontent.com/51794014/125889187-31ddb120-0555-4a1f-85d9-ea9032fd8dc8.png)

VSCode console says the following:

```
[WakaTime][ERROR] /home/simtoon/.wakatime/wakatime-cli/wakatime-cli: 1: /home/simtoon/.wakatime/wakatime-cli/wakatime-cli: �7@8@@@@@@��@@@@�u�u: not found/home/simtoon/.wakatime/wakatime-cli/wakatime-cli: 1: /home/simtoon/.wakatime/wakatime-cli/wakatime-cli: ��: not found/home/simtoon/.wakatime/wakatime-cli/wakatime-cli: 1: /home/simtoon/.wakatime/wakatime-cli/wakatime-cli: ��@@DDP�td�e�e@�e@ttQ�td/lib64/ld-linux-x86-64.so.2GNU: not found/home/simtoon/.wakatime/wakatime-cli/wakatime-cli: 1: /home/simtoon/.wakatime/wakatime-cli/wakatime-cli: +Pz: not found/home/simtoon/.wakatime/wakatime-cli/wakatime-cli: 1: /home/simtoon/.wakatime/wakatime-cli/wakatime-cli: cannot create E@@�u�uXHzlibdl.so.2_ITM_deregisterTMCloneTable__gmon_start___Jv_RegisterClasses_ITM_registerTMCloneTabledlsymdlopendlerrorlibz.so.1inflateinflateInit_inflateEndlibc.so.6__stpcpy_chk__xpg_basenamemkdtempfflushstrcpyfchmodreaddirsetlocalefopenwcsncpystrncmp__strdupperrorclosedirftellsignalstrncpymbstowcsforkunlinkmkdirstdingetpidkillstrtokfeofcallocstrlenmemsetdirnamermdirfseekclearerrunsetenv__fprintf_chkstdoutstrnlenfclose__vsnprintf_chkmallocstrcatrealpathraise__strncpy_chknl_langinfoopendirgetenvstderr__snprintf_chk__strncat_chkexecvpstrncat__realpath_chkfilenofwritefreadwaitpidstrchr__vfprintf_chk__strcpy_chk__xstat__strcat_chksetbufstrcmp__libc_start_mainferrorstpcpyfreeGLIBC_2.2.5GLIBC_2.3GLIBC_2.4GLIBC_2.3.4: File name too long/home/simtoon/.wakatime/wakatime-cli/wakatime-cli: 1: /home/simtoon/.wakatime/wakatime-cli/wakatime-cli: ELF: not found/home/simtoon/.wakatime/wakatime-cli/wakatime-cli: 1: /home/simtoon/.wakatime/wakatime-cli/wakatime-cli: Syntax error: word unexpected (expecting ")")
```
Furthermore, it reports the following:
```
[WakaTime][ERROR] Error: Command failed: /home/simtoon/.wakatime/wakatime-cli/wakatime-cli --entity /home/simtoon/terminalInsanityCLI/terminalInsanityCONSOLE/zshVerify --plugin "vscode/1.59.0-insider vscode-wakatime/14.0.0" --alternate-project terminalInsanityCLI/home/simtoon/.wakatime/wakatime-cli/wakatime-cli: 1: /home/simtoon/.wakatime/wakatime-cli/wakatime-cli: �7@8@@@@@@��@@@@�u�u: not found/home/simtoon/.wakatime/wakatime-cli/wakatime-cli: 1: /home/simtoon/.wakatime/wakatime-cli/wakatime-cli: ��: not found/home/simtoon/.wakatime/wakatime-cli/wakatime-cli: 1: /home/simtoon/.wakatime/wakatime-cli/wakatime-cli: ��@@DDP�td�e�e@�e@ttQ�td/lib64/ld-linux-x86-64.so.2GNU: not found/home/simtoon/.wakatime/wakatime-cli/wakatime-cli: 1: /home/simtoon/.wakatime/wakatime-cli/wakatime-cli: +Pz: not found/home/simtoon/.wakatime/wakatime-cli/wakatime-cli: 1: /home/simtoon/.wakatime/wakatime-cli/wakatime-cli: cannot create E@@�u�uXHzlibdl.so.2_ITM_deregisterTMCloneTable__gmon_start___Jv_RegisterClasses_ITM_registerTMCloneTabledlsymdlopendlerrorlibz.so.1inflateinflateInit_inflateEndlibc.so.6__stpcpy_chk__xpg_basenamemkdtempfflushstrcpyfchmodreaddirsetlocalefopenwcsncpystrncmp__strdupperrorclosedirftellsignalstrncpymbstowcsforkunlinkmkdirstdingetpidkillstrtokfeofcallocstrlenmemsetdirnamermdirfseekclearerrunsetenv__fprintf_chkstdoutstrnlenfclose__vsnprintf_chkmallocstrcatrealpathraise__strncpy_chknl_langinfoopendirgetenvstderr__snprintf_chk__strncat_chkexecvpstrncat__realpath_chkfilenofwritefreadwaitpidstrchr__vfprintf_chk__strcpy_chk__xstat__strcat_chksetbufstrcmp__libc_start_mainferrorstpcpyfreeGLIBC_2.2.5GLIBC_2.3GLIBC_2.4GLIBC_2.3.4: File name too long/home/simtoon/.wakatime/wakatime-cli/wakatime-cli: 1: /home/simtoon/.wakatime/wakatime-cli/wakatime-cli: ELF: not found/home/simtoon/.wakatime/wakatime-cli/wakatime-cli: 1: /home/simtoon/.wakatime/wakatime-cli/wakatime-cli: Syntax error: word unexpected (expecting ")")
```

At the end, it says this:
```
[WakaTime][ERROR] Unknown Error (2); Check your /home/simtoon/.wakatime.log file for more details (at t.Logger.log (/home/simtoon/.vscode-insiders/extensions/wakatime.vscode-wakatime-14.0.0/dist/extension.js:2:723869))
```

As I said, the log mentioned above is empty.

**Comment by alanhamlett** [comment]
Actually, never mind. The issue is in vscode, where it's downloading the correct Linux arm64 wakatime-cli binary but then using `wakatime-cli-linux-amd64` when trying running it.

**Comment by alanhamlett** [comment]
@simonSlamka can you also add this line after the current `console.log` you've already added:

`console.log(typeof arch);`

**Comment by simonSlamka** [comment]
> @simonSlamka can you also add this line after the current `console.log` you've already added:
> 
> `console.log(typeof arch);`

the output of os.arch() is a string

**Comment by alanhamlett** [comment]
@simonSlamka you have the legacy python wakatime-cli disabled in your `~/.wakatime.cfg` file?

**Comment by alanhamlett** [comment]
We had the new Go wakatime-cli disabled when sending heartbeats, but we still used it when fetching status bar code stats. Fixed with f56f87d2a498e3114e5e40784c50097b700db4a5.

**Comment by simonSlamka** [comment]
@alanhamlett no, not explicitly. the version is v1.18.9

**Comment by alanhamlett** [comment]
Restarting vscode should fix it for you. However, the problem will return once we re-launch the new Go wakatime-cli. To fix this for later, you'll have to re-do the symlink from [this comment](https://github.com/wakatime/vscode-wakatime/issues/216#issuecomment-881720890) then add these console.log lines to `src/dependencies.ts`:

```
 34     this.global = global;
 35     console.log(this.architecture());
 36   }
```

```
437   private architecture(): string {
438     const arch = os.arch();
439     console.log(typeof arch);
440     if (arch.indexOf('32') > -1) return '386';
```

**Comment by simonSlamka** [comment]
I pulled from origin and rebuilt, then copied the extension to the vscode dir. Still the same problem, it seems. Even the output is identical.

https://github.com/wakatime/vscode-wakatime/issues/216#issuecomment-882106515

(except for the console.log we added)

**Comment by jerome-diver** [comment]
> Thanks! This isn't a vscode bug. Looks like a problem with the Linux arm64 build of wakatime-cli.

I think not, because wakatime is working in my system with VIM, but not with VS Code. It is a specific bug with VS Code Wakatime plugin that call something wrongly (it looks like). What is your argument to let you thinking it is not the plugin that has a problem ? Why does wakatime (so its client) is working with other editors then ?

**Comment by alanhamlett** [comment]
Yes, my [next comment](https://github.com/wakatime/vscode-wakatime/issues/216#issuecomment-882363302) clarifies. I've deleted that wrong comment, you can ignore it since it's not correct.

**Comment by alanhamlett** [comment]
> I pulled from origin and rebuilt, then copied the extension to the vscode dir. Still the same problem, it seems. Even the output is identical.
> 
> [#216 (comment)](https://github.com/wakatime/vscode-wakatime/issues/216#issuecomment-882106515)
> 
> (except for the two `console.log`'s we added)

What's the output from `console.log(this.architecture())`?

**Comment by alanhamlett** [comment]
I found the problem, it's because the legacy wakatime-cli doesn't support arm! You should enable the new Go wakatime-cli with this line in your `~/.wakatime.cfg` file:

```
new_beta_cli = true
```

Also, make sure to update the extension to v14.0.3 (latest version in the marketplace released Today) and restart VS Code.

Can you see if that fixes it for you?

**Comment by jerome-diver** [comment]
ok @alanhamlett it's fine now, i did what you said. Thank you very much to find and fix the problem.
But please, let us know if at next step we would have to modify the wakatime.cfg file again with something other.

**Comment by alanhamlett** [comment]
Nothing will be needed in the future, as this just enables the beta wakatime-cli before it's launched to everyone. When it's launched, the config change won't be needed anymore but it won't hurt to leave it there.

**Comment by simonSlamka** [comment]
Got it.
