### ISSUE TITLE
Stuck in WakaTime Initialzing

### ISSUE THREAD

**Issue by neyser95** [wakatime/vscode-wakatime#84]
Hi,

I've been using WakaTime for around a week but I soon saw that it was capturing any of my times. Only the first day that I installed it. I followed the debugging instructions and I saw it the error it was giving me. I'm using vscode and the error I get is '[WakaTime.vscode-wakatime]Cannot read property 'fsPath' of undefined'. I don't know if it can't find some sort of file but I tried uninstalling it and then installing again but I ran into the same error. Any chance that there is a solution to this?
 
<img width="839" alt="screen shot 2019-02-23 at 11 00 58 am" src="https://user-images.githubusercontent.com/33912125/53288767-9e10db80-375a-11e9-86d8-860ec892cd51.png">

**Comment by queer** [comment]
Seeing the same thing on Linux, reinstalling/reloading the extension doesn't fix it. Version 1.2.7

**Comment by neyser95** [comment]
Yeah I tried everything and no luck.

**Comment by aligg** [comment]
I'm experiencing the same issue - new user excited about trying this out, but just stuck on wakatime initializing.

**Comment by aligg** [comment]
Had some more time this evening to look at the error logs: For me the error I'm getting is `Cannot read property 'fsPath' of undefined` hope that helps!

**Comment by alanhamlett** [comment]
This is probably related to the new release using webpack to bundle imports. Will release a fix today.

**Comment by alanhamlett** [comment]
Should be fixed with v1.2.8 that was just released.

**Comment by aligg** [comment]
Thanks Alan! I still get the same error while in v1.2.8 - any ideas?

**Comment by alanhamlett** [comment]
How about after afa3bf100f034d5bad7d406ce4cd442a6d7eb6c9 in v1.2.9?

**Comment by aligg** [comment]
no dice for me, but new error at least! `tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80` and ` [ERROR] pyenv: python3: command not found` for me, continues to be stuck in initializing.

**Comment by kreigne** [comment]
Same problem here, stuck on `WakaTime Initializing...` status. I'm running VS Code version 1.31 on macOS 10.12.6.

Extension info:
```Name: WakaTime
Id: wakatime.vscode-wakatime
Description: Metrics, insights, and time tracking automatically generated from your programming activity.
Version: 1.2.9
Publisher: WakaTime
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=WakaTime.vscode-wakatime```

Erro log:
![image](https://user-images.githubusercontent.com/26656/53902614-80236080-400f-11e9-96d4-6bcda178e6ac.png)

**Comment by alanhamlett** [comment]
Can you turn on debug mode with `CMD+SHIFT+p`, `wakatime.debug`, set to `true`, press `Enter`.

Then restart VS Code and paste the debug logs from the developer console window here?

**Comment by aligg** [comment]
Extension Host] [WakaTime] [DEBUG] Initializing WakaTime v1.2.9
console.ts:136 [Extension Host] [WakaTime] [DEBUG] Looking for python at: /Users/aliglenesk/Library/Application Support/Code/User/workspaceStorage/c8161ea240971a4b6bafaa456888a0cb/WakaTime.vscode-wakatime/python/pythonw
console.ts:136 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:136 [Extension Host] [WakaTime] [DEBUG] Looking for python at: python3
console.ts:136 [Extension Host] [WakaTime] [DEBUG] Valid python version: Python 3.6.5

console.ts:136 [Extension Host] [WakaTime] [DEBUG] Downloading wakatime-core...
mainThreadExtensionService.ts:43 [WakaTime.vscode-wakatime]tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:43
e._doInvokeHandler @ rpcProtocol.ts:265
e._invokeHandler @ rpcProtocol.ts:250
e._receiveRequest @ rpcProtocol.ts:196
e._receiveOneMessage @ rpcProtocol.ts:178
(anonymous) @ rpcProtocol.ts:111
(anonymous) @ rpcProtocol.ts:307
e.fire @ event.ts:140
(anonymous) @ ipc.net.ts:81
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
mainThreadExtensionService.ts:44 Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80
	at ClientRequest.<anonymous> (/Users/aliglenesk/.vscode/extensions/WakaTime.vscode-wakatime-1.2.9/dist/extension.js:210:246073)
	at Object.onceWrapper (events.js:293:19)
	at emitOne (events.js:96:13)
	at ClientRequest.emit (events.js:191:7)
	at Socket.socketErrorListener (_http_client.js:358:9)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at emitErrorNT (net.js:1283:8)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:44
e._doInvokeHandler @ rpcProtocol.ts:265
e._invokeHandler @ rpcProtocol.ts:250
e._receiveRequest @ rpcProtocol.ts:196
e._receiveOneMessage @ rpcProtocol.ts:178
(anonymous) @ rpcProtocol.ts:111
(anonymous) @ rpcProtocol.ts:307
e.fire @ event.ts:140
(anonymous) @ ipc.net.ts:81
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
log.ts:171   ERR socket hang up: Error: socket hang up
	at createHangUpError (_http_client.js:302:15)
	at Socket.socketCloseListener (_http_client.js:334:23)
	at emitOne (events.js:101:20)
	at Socket.emit (events.js:191:7)
	at TCP._handle.close [as _onclose] (net.js:510:12)

**Comment by alanhamlett** [comment]
Try upgrading to v1.2.11 and it should work. Turns out [ExtensionContext.storagePath](https://code.visualstudio.com/api/references/vscode-api#ExtensionContext.storagePath) isn't available on certain platforms which is why I wasn't able to reproduce it on my machine.

**Comment by queer** [comment]
Looks fixed as of v1.2.12 :+1:

**Comment by ricokahler** [comment]
I've tried v1.2.12 and it's still broken for me. I haven't got this to work for around 3 weeks now.

![image](https://user-images.githubusercontent.com/10551026/54066420-634c8000-41fd-11e9-9eb8-c5e9d7c10989.png)

here's a line from the logs:

```json
{
  "now": "2019/03/08 23:43:01 -0500",
  "version": "10.8.0",
  "plugin": "vscode/1.32.1 vscode-wakatime/1.2.12",
  "time": 1552106580.9384892,
  "caller": "/Users/ricokahler/.vscode/extensions/wakatime.vscode-wakatime-1.2.12/wakatime-master/wakatime/api.py",
  "lineno": 125,
  "file": "/Users/ricokahler/workspace/resift/src/combineLoadingStates/combineLoadingStates.ts",
  "level": "WARNING",
  "message": "{'SSLError': 'HTTPSConnectionPool(host=\\'api.wakatime.com\\', port=443): Max retries exceeded with url: /api/v1/users/current/heartbeats.bulk (Caused by SSLError(\"Can\\'t connect to HTTPS URL because the SSL module is not available.\"))', 'traceback': 'Traceback (most recent call last):\\n  File \"/Users/ricokahler/.vscode/extensions/wakatime.vscode-wakatime-1.2.12/wakatime-master/wakatime/packages/urllib3/connectionpool.py\", line 589, in urlopen\\n    conn = self._get_conn(timeout=pool_timeout)\\n  File \"/Users/ricokahler/.vscode/extensions/wakatime.vscode-wakatime-1.2.12/wakatime-master/wakatime/packages/urllib3/connectionpool.py\", line 251, in _get_conn\\n    return conn or self._new_conn()\\n  File \"/Users/ricokahler/.vscode/extensions/wakatime.vscode-wakatime-1.2.12/wakatime-master/wakatime/packages/urllib3/connectionpool.py\", line 827, in _new_conn\\n    raise SSLError(\"Can\\'t connect to HTTPS URL because the SSL \"\\nurllib3.exceptions.SSLError: Can\\'t connect to HTTPS URL because the SSL module is not available.\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/Users/ricokahler/.vscode/extensions/wakatime.vscode-wakatime-1.2.12/wakatime-master/wakatime/packages/requests/adapters.py\", line 440, in send\\n    timeout=timeout\\n  File \"/Users/ricokahler/.vscode/extensions/wakatime.vscode-wakatime-1.2.12/wakatime-master/wakatime/packages/urllib3/connectionpool.py\", line 639, in urlopen\\n    _stacktrace=sys.exc_info()[2])\\n  File \"/Users/ricokahler/.vscode/extensions/wakatime.vscode-wakatime-1.2.12/wakatime-master/wakatime/packages/urllib3/util/retry.py\", line 388, in increment\\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\\nurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=\\'api.wakatime.com\\', port=443): Max retries exceeded with url: /api/v1/users/current/heartbeats.bulk (Caused by SSLError(\"Can\\'t connect to HTTPS URL because the SSL module is not available.\"))\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/Users/ricokahler/.vscode/extensions/wakatime.vscode-wakatime-1.2.12/wakatime-master/wakatime/api.py\", line 111, in send_heartbeats\\n    verify=ssl_verify)\\n  File \"/Users/ricokahler/.vscode/extensions/wakatime.vscode-wakatime-1.2.12/wakatime-master/wakatime/packages/requests/sessions.py\", line 555, in post\\n    return self.request(\\'POST\\', url, data=data, json=json, **kwargs)\\n  File \"/Users/ricokahler/.vscode/extensions/wakatime.vscode-wakatime-1.2.12/wakatime-master/wakatime/packages/requests/sessions.py\", line 508, in request\\n    resp = self.send(prep, **send_kwargs)\\n  File \"/Users/ricokahler/.vscode/extensions/wakatime.vscode-wakatime-1.2.12/wakatime-master/wakatime/packages/requests/sessions.py\", line 618, in send\\n    r = adapter.send(request, **kwargs)\\n  File \"/Users/ricokahler/.vscode/extensions/wakatime.vscode-wakatime-1.2.12/wakatime-master/wakatime/packages/requests/adapters.py\", line 506, in send\\n    raise SSLError(e, request=request)\\nwakatime.packages.requests.exceptions.SSLError: HTTPSConnectionPool(host=\\'api.wakatime.com\\', port=443): Max retries exceeded with url: /api/v1/users/current/heartbeats.bulk (Caused by SSLError(\"Can\\'t connect to HTTPS URL because the SSL module is not available.\"))\\n'}"
}
```

and i think this issue may be related: https://github.com/wakatime/vscode-wakatime/issues/51

let me know if you need any info!

**Comment by alanhamlett** [comment]
@ricokahler I've created a new issue for you here: #86

**Comment by MaffooBristol** [comment]
@alanhamlett I'm having the initialization issue too, but the weird thing is wakatime works fine on Sublime. It's only in vscode. It also isn't sending anything to the .log file or to the vscode debugger...

**Comment by MaffooBristol** [comment]
Huh, closed my workspace and re-opened it and it fixed it. However closing vscode and even restarting my computer _didn't_. Kooky.

**Comment by gandarez** [comment]
@MaffooBristol it was a temporary malfunction.

**Comment by plavi88** [comment]
Hi all,

I just installed wakatime to VS Code but it got stuck at initializing. I followed the instructions for troubleshooting and this is what I am getting:

![Screen Shot 2020-08-24 at 12 58 27 PM](https://user-images.githubusercontent.com/57862695/91037577-86ddd300-e609-11ea-990e-10807afa1f64.png)

Could you please help?

Thanks

**Comment by pcomino** [comment]
@plavi88 Same here for me. Stuck on "Downloading wakatime-cli standalone..." for me.

**Comment by cosmaioan** [comment]
same for me. Reinstall did not solve problem. 
![image](https://user-images.githubusercontent.com/2738404/91045255-48531300-e61f-11ea-8dc8-0e6659dea30a.png)

**Comment by cosmaioan** [comment]
> same for me. Reinstall did not solve problem.
> ![image](https://user-images.githubusercontent.com/2738404/91045255-48531300-e61f-11ea-8dc8-0e6659dea30a.png)

I downgraded to 4.0.0 and it works 
![image](https://user-images.githubusercontent.com/2738404/91046622-7174a300-e621-11ea-9828-6acc049750c0.png)

**Comment by agrotech-cowboy** [comment]
> I downgraded to 4.0.0 and it works
> ![image](https://user-images.githubusercontent.com/2738404/91046622-7174a300-e621-11ea-9828-6acc049750c0.png)

How did you downgrade?

**Comment by alanhamlett** [comment]
Duplicate of #156, fixed in v4.0.5 which was released just now.
